# Generated by Django 4.2.29 on 2026-03-22 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso corporal (kg)'),
        ),
        migrations.CreateModel(
            name='BodyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% grasa corporal')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrica corporal',
                'verbose_name_plural': 'Métricas corporales',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
