# Generated by Django 6.0.3 on 2026-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='distance_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distancia (m)'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración (seg)'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='reps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Repeticiones'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)'),
        ),
    ]
