# Generated by Django 4.2.29 on 2026-03-22 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_met_value_exercise_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout_sessions', '0002_exerciseset_distance_meters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('record_type', models.CharField(choices=[('max_weight', 'Peso máximo'), ('max_reps', 'Máx. repeticiones'), ('max_volume', 'Volumen máximo'), ('best_distance', 'Mejor distancia')], max_length=20)),
                ('achieved_at', models.DateField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Récord personal',
                'verbose_name_plural': 'Récords personales',
                'ordering': ['exercise__name', 'record_type'],
                'unique_together': {('user', 'exercise', 'record_type')},
            },
        ),
    ]
