# Generated by Django 6.0.3 on 2026-03-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('plan_type', models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual')], default='weekly', max_length=20, verbose_name='Tipo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de entrenamiento',
                'verbose_name_plural': 'Planes de entrenamiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('sets', models.IntegerField(default=3, verbose_name='Series')),
                ('reps', models.IntegerField(default=10, verbose_name='Repeticiones')),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso objetivo (kg)')),
                ('rest_seconds', models.IntegerField(default=60, verbose_name='Descanso (seg)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicio del plan',
                'verbose_name_plural': 'Ejercicios del plan',
                'ordering': ['day_of_week', 'order'],
            },
        ),
    ]
