# Generated by Django 4.2.29 on 2026-03-21 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='visibility',
            field=models.CharField(choices=[('general', 'General (visible para todos)'), ('particular', 'Particular (solo para el asignado)'), ('personal', 'Personal (solo para mí)')], default='particular', max_length=20, verbose_name='Visibilidad'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
    ]
