# Generated by Django 6.0.3 on 2026-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('exercise_type', models.CharField(choices=[('strength', 'Fuerza'), ('cardio', 'Cardio'), ('flexibility', 'Flexibilidad')], default='strength', max_length=20, verbose_name='Tipo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Imagen')),
                ('is_public', models.BooleanField(default=True, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chest', 'Pecho'), ('back', 'Espalda'), ('legs', 'Piernas'), ('shoulders', 'Hombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('core', 'Core/Abdomen'), ('cardio', 'Cardio'), ('glutes', 'Glúteos'), ('calves', 'Gemelos'), ('forearms', 'Antebrazos'), ('full_body', 'Cuerpo completo')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo muscular',
                'verbose_name_plural': 'Grupos musculares',
            },
        ),
    ]
