# Generated by Django 4.2.29 on 2026-03-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='met_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor MET (calorías)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL vídeo técnica (YouTube)'),
        ),
    ]
