# Generated by Django 4.2.29 on 2026-04-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_met_value_exercise_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rest_time',
            field=models.IntegerField(default=30, verbose_name='Tiempo de descanso entre series (segundos)'),
        ),
    ]
